//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaltyCalculation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CountryHoliday = new HashSet<CountryHoliday>();
        }
    
        public int id { get; set; }
        public byte deleted { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<CountryHoliday> CountryHoliday { get; set; }
    }
}
